# Generated by Django 2.0.4 on 2018-04-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180426_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='investigator',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
