# Generated by Django 2.0.4 on 2018-04-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180426_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='investigator',
        ),
        migrations.AddField(
            model_name='position',
            name='firstname',
            field=models.CharField(default='NULL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='lastname',
            field=models.CharField(default='NULL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='title',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
